#include "pomp_lib.h"

struct ompregdescr omp_rd_15 = {
  "parallel", "", 0, "simpar.c", 33, 33, 146, 146
};

#define POMP_DLIST_00015 shared(omp_rd_15,omp_rd_16,omp_rd_17,omp_rd_18,omp_rd_19,omp_rd_20,omp_rd_21,omp_rd_22,omp_rd_23,omp_rd_24,omp_rd_25)

struct ompregdescr omp_rd_16 = {
  "for", "", 0, "simpar.c", 39, 39, 45, 45
};

struct ompregdescr omp_rd_17 = {
  "for", "", 0, "simpar.c", 54, 54, 80, 80
};

struct ompregdescr omp_rd_18 = {
  "atomic", "", 0, "simpar.c", 63, 63, 64, 64
};

struct ompregdescr omp_rd_19 = {
  "atomic", "", 0, "simpar.c", 65, 65, 66, 66
};

struct ompregdescr omp_rd_20 = {
  "atomic", "", 0, "simpar.c", 67, 67, 68, 68
};

struct ompregdescr omp_rd_21 = {
  "atomic", "", 0, "simpar.c", 74, 74, 75, 75
};

struct ompregdescr omp_rd_22 = {
  "atomic", "", 0, "simpar.c", 76, 76, 77, 77
};

struct ompregdescr omp_rd_23 = {
  "atomic", "", 0, "simpar.c", 78, 78, 79, 79
};

struct ompregdescr omp_rd_24 = {
  "for", "", 0, "simpar.c", 82, 82, 87, 87
};

struct ompregdescr omp_rd_25 = {
  "for", "", 0, "simpar.c", 91, 91, 145, 145
};

struct ompregdescr omp_rd_26 = {
  "parallel", "", 0, "simpar.c", 149, 149, 169, 169
};

#define POMP_DLIST_00026 shared(omp_rd_26,omp_rd_28)

struct ompregdescr omp_rd_27 = {
  "parallelfor", "", 0, "simpar.c", 155, 155, 160, 160
};

#define POMP_DLIST_00027 shared(omp_rd_27)

struct ompregdescr omp_rd_28 = {
  "single", "", 0, "simpar.c", 162, 162, 168, 168
};

